RHEcosystemAppEng/dbaas-operator

- go.mod
- go.sum
Updating atlas operator reference to point to our week 2 dbaas demo tag
> updating atlas ref to week 2 demo version

- api/v1alpha1/dbaasprovider.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/dbaas.redhat.com_dbaasconnections.yaml
> Change DBaaSConnectionStatus.CredentialsRef to optional

- config/manager/manager.yaml
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
- controllers/dbaas_reconciler.go
- controllers/dbaasconnection_controller.go
- controllers/dbaasinventory_controller.go
- controllers/mapstructure_utils.go
- controllers/suite_test.go
- main.go
1. hide DBaaSConnection from OLM: https://issues.redhat.com/browse/DBAAS-99
2. update dbaas-operator to be cluster-scoped: https://issues.redhat.com/browse/DBAAS-95
> DBaaS-95&99: Update dbaas-operator to be cluster-scoped, hide DBaaSConnection from OLM

- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
~~Unit tests added that prove the fix is effective or the feature works~~
> [DBAAS-109] suggest openshift-dbaas-operator namespace

- api/v1alpha1/dbaasconnection_types.go
- api/v1alpha1/dbaasinventory_types.go
- config/crd/kustomization.yaml
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/dbaas_reconciler.go
- controllers/dbaasconnection_controller.go
- controllers/dbaasinventory_controller.go
- go.mod
- go.sum
Restore zero-replica deployment owned by Connection resource
Jira: https://issues.redhat.com/browse/DBAAS-107
> DBAAS-107: restore zero-replica deployment owned by Connection resource

- config/manager/manager.yaml
- controllers/dbaas_reconciler.go
- controllers/dbaasconnection_controller.go
- controllers/dbaasinventory_controller.go
- controllers/dbaasprovider_controller.go
- main.go
Watch the provider ConfigMaps changes and re-deploy DBaaS operator
Jira: https://issues.redhat.com/browse/DBAAS-69
> DBAAS-69: watch DBaaSProvider inventory and connection CRs 

- README.md
updating dbaasservice to say dbaasinventory
> update to show dbaasinventory instead of dbaasservice

- controllers/dbaasinventory_controller.go
add verbosity to info logger in inventory controller. Defaulting to 1 which is equivalent to zap level debug.
- [X ] New feature (non-breaking change which adds functionality)
> add verbosity to info logger in inventory controller

- .github/workflows/gobuild.yml
> add github action for unit tests and generation checks

- api/v1alpha1/dbaasconnection_webhook_test.go
- api/v1alpha1/webhook_suite_test.go
- controllers/dbaas_controllers_common_test.go
- controllers/dbaas_reconciler.go
- controllers/dbaas_reconciler_test.go
- controllers/dbaasconnection_controller.go
- controllers/dbaasconnection_controller_test.go
- controllers/dbaasinventory_controller.go
- controllers/dbaasinventory_controller_test.go
- controllers/dbaasprovider_controller.go
- controllers/dbaasprovider_controller_test.go
- controllers/dbaastenant_controller.go
- controllers/dbaastenant_controller_test.go
- controllers/suite_test.go
- go.mod
- test/crd/dbaas.redhat.com_crunchybridgeconnections.yaml
- test/crd/dbaas.redhat.com_crunchybridgeinventories.yaml
- test/crd/dbaas.redhat.com_mongodbatlasconnections.yaml
- test/crd/dbaas.redhat.com_mongodbatlasinventories.yaml
Add tests for the controllers
Jira: https://issues.redhat.com/browse/DBAAS-70
> DBAAS-70: add tests for the controllers

- controllers/dbaas_reconciler.go
- controllers/dbaas_reconciler_test.go
- controllers/dbaastenant_controller.go
Index the field `inventoryNamespace` of `DBaaSTenant`.
> Index inventoryNamespace of DBaaSTenant

- Makefile
- bundle.Dockerfile
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
- config/samples/catalog-source.yaml
Updating our operator's details page for OLM catalog. I also had to push version up due to iterating the bundle with these changes as I tested them.
> updating OLM catalog details for operator

- .github/workflows/golangci-lint.yml
- controllers/reconcilers/crunchybridge_installation/crunchybridge_installation_reconciler.go
- controllers/reconcilers/csv/csv_reconciler.go
- controllers/reconcilers/mongodb_atlas_instalation/mongodb_atlas_installation_reconciler.go
- controllers/reconcilers/servicebinding/servicebinding_reconciler.go
- Adding gosec github action - https://github.com/securego/gosec
- Also, fixing found vulnerability - https://cwe.mitre.org/data/definitions/118.html
> add gosec gh action

- README.md
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
- [ X] Bug fix (non-breaking change which fixes an issue)
> Update product name to Red Hat OpenShift Database Access

- controllers/reconcilers/constants.go
> updated the image org for crunchy bridge provider

- controllers/reconcilers/constants.go
> leverage versioned UI plugin image

- controllers/reconcilers/constants.go
updated the image of crunchy bridge operator from registry (registry.developers.crunchydata.com). and tested it as works fine see below screen 
- catalog source image pulling and installing  :
- operator installation :
MongoDB image update :
> updated crunchy-bridge-operator and mongodb-atlas operator image

- controllers/reconcilers/console_plugin/plugin_installation_reconciler.go
Updating plugin replicas from 1 to 3 to align with SRE guidelines.
> DBAAS-170: Updated replicas from 1 to 3

- Dockerfile
> add LICENSE to image

- controllers/dbaas_reconciler.go
- controllers/dbaas_reconciler_test.go
- controllers/dbaastenant_authorization.go
Before updating existing rbac objects, verify they are owned by relevant tenants/inventories. We don't want the operator making changes to existing, user-created objects.
> verify existing k8s objects are owned by operator objects before updating

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
> increase memory limit

- controllers/dbaastenant_authorization.go
https://github.com/RHEcosystemAppEng/dbaas-operator/pull/39 was merged before rebase was ready
> fix owned PR merge

- controllers/reconcilers/constants.go
Temporary updating the image org to use from ecosystem-appeng, to support new  API changes in Crunchy Bridge operator. 
Note: this change will be reverted once, the latest changes will push to the crunchy data image registry. 
> update the image for crunchy to use from ecosystem-appeng

- controllers/dbaas_reconciler.go
- controllers/dbaasconnection_controller.go
- controllers/dbaasinventory_controller.go
- controllers/dbaasprovider_controller.go
- controllers/dbaastenant_authorization.go
- controllers/reconcilers/csv.go
verbosity is additive and is currently sending these logs to DEBUG instead of INFO.
> change log messages to INFO

- api/v1alpha1/dbaastenant_types.go
- bundle/manifests/dbaas.redhat.com_dbaastenants.yaml
- config/crd/bases/dbaas.redhat.com_dbaastenants.yaml
- controllers/dbaastenant_authorization.go
> addt'l inventory namespace validation

- controllers/dbaas_controllers_common_test.go
- controllers/dbaas_reconciler_test.go
- controllers/dbaasprovider_controller_test.go
- controllers/suite_test.go
Jira: https://issues.redhat.com/browse/DBAAS-238
> DBAAS-238: Fix unit test recurring issues

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
> minor kustomize changes

- controllers/suite_test.go
> increase test timeout

- api/v1alpha1/dbaasinventory_webhook.go
- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/dbaas_reconciler.go
- controllers/dbaas_reconciler_test.go
- controllers/dbaasconnection_controller_test.go
- controllers/dbaasinstance_controller_test.go
- controllers/dbaasinventory_controller.go
- controllers/dbaasinventory_controller_test.go
> properly label provider credential secrets

- api/v1alpha1/dbaasplatform_types.go
- controllers/dbaasplatform_controller.go
- controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
- controllers/reconcilers/constants.go
- controllers/reconcilers/mongodb_atlas_installation/mongodb_atlas_installation_reconciler.go
> Add cockroachdb cloud operator to dbaas platform

- api/v1alpha1/dbaasprovider.go
- bundle/manifests/dbaas.redhat.com_dbaasinstances.yaml
- config/crd/bases/dbaas.redhat.com_dbaasinstances.yaml
- controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> correct cockroachdb deployment name

- controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
- controllers/reconcilers/crunchybridge_installation/crunchybridge_installation_reconciler.go
- controllers/reconcilers/mongodb_atlas_installation/mongodb_atlas_installation_reconciler.go
- controllers/reconcilers/olm_helper.go
- controllers/reconcilers/olm_helper_test.go
> code refactor, added generic functions

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
> hide dbass-instance CR from OLM

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
- controllers/reconcilers/console_plugin/plugin_installation_reconciler.go
Improvements recommended by prod sec team. Unable to add probes for kube rbac proxy container due to following known issue.
https://github.com/kubernetes/kubernetes/issues/43784
> [DBAAS-188] security related changes 

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
> Increase memory and cpu limit for DBaaS Operator

- README.md
> Make visibility of the repositories public

- README.md
> Replace ORG with QUAY_ORG

- api/v1alpha1/dbaasplatform_types.go
- api/v1alpha1/dbaasprovider.go
- controllers/dbaasplatform_controller.go
- controllers/reconcilers/constants.go
This PR is for the left over of previous PR:
https://github.com/RHEcosystemAppEng/dbaas-operator/pull/121
Deploy DBaaS Operator. Verify all provider operators and console plugins are deployed successfully.
- [X ] all relevant tests are passing
- [ X] Code Review completed
- [ X] Verified independently by reviewer
> DBaaS Operator installation further refactoring

- controllers/reconcilers/constants.go
> update the crunchy bridge image v0.0.2-rc.0

- controllers/reconcilers/quickstart_installation/getting-started-with-openshift-database-access-for-administrators-quick-start.yaml
- controllers/reconcilers/quickstart_installation/getting-started-with-openshift-database-access-for-developers-quick-start.yaml
Minor updates to the quick-start guides based on feedback.
Reviewed the QSG updates in a shared OCP cluster in the QuickLab environment.
> Minor QSG updates

- controllers/reconcilers/constants.go
update for crdb to use its official catalog image
> update for crdb to use its official catalog image

- controllers/reconcilers/constants.go
> updated mongodb provider image as v0.2.0

- controllers/reconcilers/constants.go
Updated image for crunchy as v0.0.2, successfully deployed as shown below screenshot. Done one round of testing 
> updated crunchybridge operator img v0.0.2

- Makefile
- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/kustomization.yaml
- controllers/reconcilers/constants.go
> increment version to 0.1.5

- .github/workflows/dockerbuild.yml
- .github/workflows/gobuild.yml
- .github/workflows/golangci-lint.yml
- controllers/dbaasconnection_controller_test.go
- controllers/dbaasinstance_controller_test.go
> fix connection/instance tests

- .github/workflows/dockerbuild.yml
- .github/workflows/gobuild.yml
- .github/workflows/golangci-lint.yml
- controllers/dbaasconnection_controller_test.go
- controllers/dbaasinstance_controller_test.go
> cherry-pick: fix connection/instance tests

- api/v1alpha1/dbaasprovider.go
- controllers/dbaas_reconciler.go
> [DBAAS-378] simplify invalid ns messaging

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/samples/dbaas_v1alpha1_dbaastenant.yaml
- controllers/dbaastenantauthz_controller_test.go
> remove authz field from tenant sample

- controllers/dbaas_controllers_common_test.go
- controllers/dbaas_reconciler.go
- controllers/dbaas_reconciler_test.go
- controllers/dbaasconnection_controller_test.go
- controllers/dbaasinstance_controller_test.go
- controllers/dbaasinventory_controller_test.go
related to https://github.com/jeremyary/ccapi-k8s-operator/pull/1
> add label patch for other providers

- controllers/dbaas_controllers_common_test.go
- controllers/dbaas_reconciler.go
- controllers/dbaas_reconciler_test.go
- controllers/dbaasconnection_controller_test.go
- controllers/dbaasinstance_controller_test.go
- controllers/dbaasinventory_controller_test.go
> release-0.1.4 cherry: add label patch for other providers

- api/v1alpha1/dbaasprovider.go
- controllers/dbaas_reconciler.go
- controllers/dbaas_reconciler_test.go
- controllers/dbaasinventory_controller_test.go
> move cred label constants

- api/v1alpha1/dbaasprovider.go
- controllers/dbaas_reconciler.go
- controllers/dbaas_reconciler_test.go
- controllers/dbaasinventory_controller_test.go
> cherry-pick: move cred label constants

- .github/workflows/golangci-lint.yml
> fix linter

- .github/workflows/golangci-lint.yml
> cherry-pick: fix linter

- controllers/reconcilers/constants.go
updated the image of crunchy bridge operator to v0.0.3, installed successfully and verified e2e flow and works as expected
> updated crunchy-bridge image to v0.0.3

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
> missing webhook in bundle generation

- controllers/reconcilers/quickstart_installation/getting-started-with-openshift-database-access-for-administrators-quick-start.yaml
Fixes: Jira [DBAAS-495](https://issues.redhat.com/browse/DBAAS-495)
Verbiage updates to the UI for patch 0.1.5.
Reviewed the QSG updates in a shared OCP cluster in the QuickLab environment.
> Verbiage edits for UI

- Makefile
- controllers/reconcilers/constants.go
> cherry-pick: handle bundle upgrades

- controllers/reconcilers/constants.go
> cherry-pick of PR#184 from release-0.1.5 to main

- api/v1alpha1/dbaasplatform_types.go
- controllers/reconcilers/constants.go
Add the RDS provider operator as dependency.
Jira: https://issues.redhat.com/browse/DBAAS-531
1. Install the DBaaS operator
2. The RDS provider operator should be installed as a dependency
> DBAAS-531: add RDS provider operator as dependency

- api/v1alpha1/dbaasinventory_webhook.go
- api/v1alpha1/dbaasinventory_webhook_test.go
- api/v1alpha1/webhook_suite_test.go
Add the RDS validation to DBaaSInventory webhook so that only one DBaaSInventory for RDS can be created.
Create one DBaaSInventory for RDS and then create a second one. The second creation should fail.
- [ X] all relevant tests are passing
- [ X] Code Review completed
- [ X] Verified independently by reviewer
> Add RDS validation to DBaaSInventory webhook to prevent more than one provider account for RDS

- controllers/dbaasconnection_controller.go
- controllers/dbaasinstance_controller.go
- controllers/dbaasinventory_controller.go
- controllers/metrics.go
with this PR : 
1- Fixed the request duration metrics for inventory, connection and instance.
2- removing/cleaning up request duration metrics if respective object deleted from cluster. 
3- code refactor
> code refactor and fixes for the request duration metrics

- controllers/reconcilers/constants.go
Signed-off-by: Rewant Soni <resoni@redhat.com>
Update Observability Opertor version
1. Install the operator after creating it.
2. Observability Operator comes with version 0.12
> Update Observability Opertor version

- Makefile
- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/kustomization.yaml
- config/samples/catalog-source.yaml
> increment version to 0.3.0

- wrapper.Dockerfile
> add /usr/sbin chmod to wrapper

- api/v1alpha1/dbaasprovider.go
- config/crd/bases/dbaas.redhat.com_dbaasproviders.yaml
- config/samples/dbaas_v1alpha1_dbaasprovider.yaml
Temp branch to move forward with dependencies
> Adding helpText to the credentialFields.

- .github/workflows/generate.yml
- .github/workflows/gotest.yml
- Makefile
> sdk install added to Makefile; generate gh action

- README.md
- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/dbaasplatform_controller.go
- controllers/metrics.go
- controllers/reconcilers/providersinstallation/observability-operator.go
- controllers/util/openshift.go
> [DBAAS-817] Added cluster related information into metrics and code refactor

- go.mod
- go.sum
https://issues.redhat.com/browse/DBAAS-279
> [DBAAS-279] upgrade prometheus/client_golang version

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/default/manager-env-images.yaml
Change will break image/build/product until all provider images have been published.
> DBAAS-584: incrementing all providers for next release

- README.md
- docs/dashboard/rhoda_grafana_dashboard.json
- docs/observability-operator-config.md
1- Added garfana dashboard file
2- Added document for observability operator configuration
> [DBAAS-331] added grafana dashboard file, document for observability operator configuration

- api/v1alpha1/dbaas.redhat.com_dbaasconnection_v1alpha1.openapi.yaml
- api/v1alpha1/dbaas.redhat.com_dbaasinstance_v1alpha1.openapi.yaml
- api/v1alpha1/dbaas.redhat.com_dbaasinventory_v1alpha1.openapi.yaml
- api/v1alpha1/dbaas.redhat.com_dbaasplatform_v1alpha1.openapi.yaml
- api/v1alpha1/dbaas.redhat.com_dbaaspolicy_v1alpha1.openapi.yaml
- api/v1alpha1/dbaas.redhat.com_dbaasprovider_v1alpha1.openapi.yaml
Updated OpenAPI spec files.
Fixes: Jira [DBAAS-832](https://issues.redhat.com/browse/DBAAS-832)
> Updated OpenAPI spec files

- controllers/dbaasconnection_controller.go
- controllers/dbaasinstance_controller.go
- controllers/metrics.go
- controllers/reconcilers/constants.go
Fixed below issues 
https://issues.redhat.com/browse/DBAAS-904
https://issues.redhat.com/browse/DBAAS-902
https://issues.redhat.com/browse/DBAAS-905
https://issues.redhat.com/browse/DBAAS-907
and 
https://issues.redhat.com/browse/DBAAS-912
> Fix the duplicate entries when connection, instance, and provider account deleted, added DBaaS QuickStart Version 

- .github/workflows/dockerbuild.yml
- .github/workflows/dockerpush.yml
> automated quay.io pushes

- .github/workflows/dockerpush.yml
> limit gh action push to upstream repo

- .github/workflows/dockerpush.yml
- Makefile
this warranted a new make command to retrieve the VERSION, which includes the hash for dev builds -
```bash
$ DEV=true make get-version
0.3.0-f9d1040
$ make get-version 
0.3.0
```
> add commit hash to dev builds & push bundle

- .github/workflows/dockerpush.yml
> add commit hash to dev builds

- .github/workflows/dockerpush.yml
> add go to push workflow

- .github/workflows/dockerpush.yml
> add catalog to push workflow

- .github/workflows/dockerpush.yml
- Makefile
> fix catalog build and push

- .github/workflows/dockerpush.yml
> remove extra catalog workflow steps

- .github/workflows/dockerpush.yml
> secret related change

- api/v1alpha1/dbaasplatform_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/dbaas.redhat.com_dbaasplatforms.yaml
- config/crd/bases/dbaas.redhat.com_dbaasplatforms.yaml
- controllers/dbaasplatform_controller.go
> revert the type name PlatformsStatus to PlatformStatus

- Makefile
- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
- config/samples/catalog-source.yaml
- controllers/reconcilers/constants.go
> increment version to 0.3.1

- Makefile
- wrapper.Dockerfile
> increment wrapper image version

- Makefile
> revert wrapper image location

- Makefile
- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
> add skipRange for test build

- Makefile
- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
> remove skipRange, use 0.2.0 wrapper

- api/v1alpha1/dbaasplatform_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/dbaas.redhat.com_dbaasplatforms.yaml
- config/crd/bases/dbaas.redhat.com_dbaasplatforms.yaml
- controllers/dbaasplatform_controller.go
Reverts RHEcosystemAppEng/dbaas-operator#253
> Revert "revert the type name PlatformsStatus to PlatformStatus"

- bundle/metadata/dependencies.yaml
> [DBAAS-940] add ack dependency to ensure seamless upgrade

- api/v1alpha1/dbaasplatform_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/dbaas.redhat.com_dbaasplatforms.yaml
- config/crd/bases/dbaas.redhat.com_dbaasplatforms.yaml
- controllers/dbaasplatform_controller.go
Reverts RHEcosystemAppEng/dbaas-operator#258
> Revert "Revert "revert the type name PlatformsStatus to PlatformStatus""

- api/v1alpha1/dbaasplatform_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/dbaas.redhat.com_dbaasplatforms.yaml
- config/crd/bases/dbaas.redhat.com_dbaasplatforms.yaml
- controllers/dbaasplatform_controller.go
Reverts RHEcosystemAppEng/dbaas-operator#262
> Revert "Revert "Revert "revert the type name PlatformsStatus to PlatformStatus"""

- controllers/reconcilers/providersinstallation/providers_installation_reconciler.go
> cherry-pick: add startingCSV to provider subscriptions

- config/samples/installation-for-OSD-OCP-environments.yaml
> sample install for osd

- 0.3.0upgrade.sh
> add wait to object deletions

- 0.3.0upgrade.sh
> use subscriptions.operators.coreos.com instead of sub alias

- 0.3.0upgrade.sh
> require oc client version 4.9 or greater

- 0.3.0upgrade.sh
> account for addons in upgrade fix script

- 0.3.0upgrade.sh
> addon fixes

- config/samples/catalog-subscription.yaml
- config/samples/installation-for-OSD-OCP-environments.yaml
> update sample install for osd

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/default/manager-env-images.yaml
upgraded the version of observability operator to v0.0.14
> upgraded the version of observability operator to v0.0.14

- Makefile
enforce use of properly versioned sdk and opm binaries
> [DBAAS-980] enforce use of properly versioned sdk and opm binaries

- backstage-config/catalog-info.yaml
Checking in the backstage configuration for testing.
> checking in the backstage configuration for testing.

- api/v1alpha1/dbaasconnection_types.go
- api/v1alpha1/dbaasinstance_types.go
- api/v1alpha1/dbaasinventory_types.go
- api/v1alpha1/dbaasplatform_types.go
- api/v1alpha1/dbaaspolicy_types.go
- api/v1alpha1/dbaasprovider.go
- api/v1alpha1/dbaasprovider_types.go
- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- bundle/manifests/dbaas.redhat.com_dbaasconnections.yaml
- bundle/manifests/dbaas.redhat.com_dbaasinstances.yaml
- bundle/manifests/dbaas.redhat.com_dbaasinventories.yaml
- bundle/manifests/dbaas.redhat.com_dbaasplatforms.yaml
- bundle/manifests/dbaas.redhat.com_dbaaspolicies.yaml
- bundle/manifests/dbaas.redhat.com_dbaasproviders.yaml
- config/crd/bases/dbaas.redhat.com_dbaasconnections.yaml
- config/crd/bases/dbaas.redhat.com_dbaasinstances.yaml
- config/crd/bases/dbaas.redhat.com_dbaasinventories.yaml
- config/crd/bases/dbaas.redhat.com_dbaasplatforms.yaml
- config/crd/bases/dbaas.redhat.com_dbaaspolicies.yaml
- config/crd/bases/dbaas.redhat.com_dbaasproviders.yaml
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
Updates the comments for API schema descriptions.
Fixes: Jira [DBAAS-1033](https://issues.redhat.com/browse/DBAAS-1033)
> Updates the comments for API schema descriptions

- bundle/metadata/dependencies.yaml
Upgrade rds-controller to v0.1.1 and support RHODA upgrade.
> DBAAS-941: upgrade to RDS controller v0.1.1

- Makefile
- README.md
- docs/api/asciidoc/ref.adoc
- docs/api/markdown/ref.md
- ref-templates/asciidoctor/gv_details.tpl
- ref-templates/asciidoctor/gv_list.tpl
- ref-templates/asciidoctor/type.tpl
- ref-templates/asciidoctor/type_members.tpl
- ref-templates/config.yaml
- ref-templates/markdown/gv_details.tpl
- ref-templates/markdown/gv_list.tpl
- ref-templates/markdown/type.tpl
- ref-templates/markdown/type_members.tpl
> automated api ref docs

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/dbaasplatform_controller.go
- go.mod
- main.go
> [OCPBUGS-4991] temporary conversion webhook fix 

- api/v1alpha1/groupversion_info.go
- api/v1beta1/dbaasconnection_types.go
- api/v1beta1/dbaasinstance_types.go
- api/v1beta1/dbaasinventory_types.go
- api/v1beta1/dbaasplatform_types.go
- api/v1beta1/dbaaspolicy_types.go
- api/v1beta1/dbaasprovider_types.go
- api/v1beta1/groupversion_info.go
- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/embed.go
- controllers/reconcilers/constants.go
> [DBAAS-891] container checks for ose-kube-rbac-proxy; increment tag

- controllers/metrics/dbaas_connection_metrics.go
- controllers/metrics/dbaas_instance_metrics.go
- controllers/metrics/dbaas_platform_metrics.go
- controllers/metrics/dbaas_policy_metrics.go
- controllers/metrics/metrics.go
Fix metrics provider parameter provided to dbaas_platform
1. Install the DBaaS Operator onto an Openshift Local cluster.
2. Expose the Prometheus service and navigate to Prometheus service route
3. Look up with dbaas_requests_duration_seconds_sum{resource="dbaas_platform"} in the search bar
4. You should see provider="none" for the dbaas_platform
> [DBAAS-1125] Fix provider param

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/manifests/bases/dbaas-operator.clusterserviceversion.yaml
> DBAAS-1149: update RHODA operatorhub email addy

- .github/workflows/dockerbuild.yml
- wrapper.Dockerfile
> upgrade 0.3.0 catalog image

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- bundle/metadata/dependencies.yaml
- config/default/manager-env-images.yaml
Upgrade to RDS controller v0.1.2
> DBAAS-941: upgrade to RDS controller v0.1.2

- api/v1beta1/dbaasplatform_types.go
- api/v1beta1/dbaaspolicy_types.go
- api/v1beta1/dbaasprovider.go
- bundle/manifests/dbaas.redhat.com_dbaasplatforms.yaml
- bundle/manifests/dbaas.redhat.com_dbaaspolicies.yaml
- bundle/manifests/dbaas.redhat.com_dbaasproviders.yaml
- config/crd/bases/dbaas.redhat.com_dbaasplatforms.yaml
- config/crd/bases/dbaas.redhat.com_dbaaspolicies.yaml
- config/crd/bases/dbaas.redhat.com_dbaasproviders.yaml
- docs/api/asciidoc/ref.adoc
- docs/api/markdown/ref.md
Updates to the API schema descriptions.
Fixes: Jira [DBAAS-1164](https://issues.redhat.com/browse/DBAAS-1164)
> Updates to the API schema descriptions and updated docs

- api/v1beta1/webhook_suite_test.go
- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/dbaasplatform_controller.go
- controllers/dbaasplatform_controller_test.go
- controllers/suite_test.go
- main.go
The aws `rds-controller` requires a configuration configmap and a credentials secret to finish install and upgrade.
The `rds-dbaas-operator` will scale it down to avoid this issue when installation, but during upgrade the `rds-dbaas-operator` is deleted. `rds-controller` will auto-upgrade,`rds-dbaas-operator` won't be installed until the `rds-controller` upgrade finishes or deleted. As a result, the upgrade will be in a dead lock if there is no rds provider account before upgrading.
The workaround is to create dummy aws secret and configmap if not exist during the `dbaas-operator` controllers installation. `ack-controller` and `rds-dbaas-operator` start upgrading after the `dbaas-operator` installation finishes.
Tested 3 scenarios:
1. fresh installation, create provider account for RDS, …
> DBAAS-1170: workaround to the rds-controller upgrade issue for release 0.0.4

- bundle/metadata/dependencies.yaml
Upgrade the RDS controller to  v0.1.3
Jira: https://issues.redhat.com/browse/DBAAS-1186
> DBAAS-1186: upgrade to RDS controller v0.1.3

- api/v1alpha1/dbaasconnection_conversion.go
- api/v1alpha1/dbaasinstance_conversion.go
- api/v1alpha1/dbaasinventory_conversion.go
- controllers/dbaas_controllers_common_test.go
- controllers/dbaasinstance_controller.go
- controllers/dbaasinstance_controller_test.go
Parse v1alpha1 provider instance spec and status.
Jira: https://issues.redhat.com/browse/DBAAS-1191
1. Create RDS Inventory
2. Create RDS Instance
> DBAAS-1191: parse v1alpha1 provider instance spec and status

- bundle/manifests/dbaas-operator.clusterserviceversion.yaml
- config/default/manager-env-images.yaml
- controllers/reconcilers/observability/observability_operator_reconciler.go
> Fixed the Dynamic plugin version and Service Monitor Port

- main.go
Add Inventory, Instance and Connection gauge registration
Create DBaaS Inventory, Instance and Connection Objects.
> [dbaas-1195] Fix DBaaS Inventory Gauge

- controllers/dbaasplatform_controller.go
- controllers/metrics/dbaas_instance_metrics.go
- controllers/metrics/metrics.go
- controllers/reconcilers/observability/observability_operator_reconciler.go
https://issues.redhat.com/browse/DBAAS-1207
> [DBAAS-1207] Fix the cluster version upgrade metrics and update implementation observability CR create/update

- Makefile
- README.md
- config/samples/catalog-source-template.yaml
Clean up the instructions on how to build and push the images.
> Simplify makefile and build instructions

- bundle/metadata/dependencies.yaml
- bundle/metadata/properties.yaml
Moving olm.constraints to new `properties.yaml` file.  This seems to do the trick for `opm migrate` and brings over the pertinent settings to file-based catalog builds for OpenShift 4.11+ registries. The hope is that this will resolve our community hub olm dependency issues w/ SBO.
```shell
diff --git a/testMigrate/dbaas-operator/catalog.json b/testMigrate/dbaas-operator/catalog.json
index 1ead2c0..abe467c 100644
--- a/testMigrate/dbaas-operator/catalog.json
+++ b/testMigrate/dbaas-operator/catalog.json
@@ -13,16 +13,40 @@
"package": "dbaas-operator",
"image": "quay.io/ecosystem-appeng/dbaas-operator-bundle:v0.5.0",
"properties": [
+        {
+            "type": "olm.constraint",
+            "value": {
+                "any": {
+                    "constraints": [
+ …
```
> [DBAAS-1255] workaround `opm migrate` issue
