RHEcosystemAppEng/dbaas-operator

.gitignore
bundle/manifests/dbaas-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/dbaasservice_controller.go
go.mod

Updates to dbaas operator to trigger the creation of a Database User. There may still be access issues with the user not reading content from the MongoDB collection
Signed-off-by: Babak Mozaffari <bmozaffa@redhat.com>

Create Atlas Database User for e2e demo

---

config/crd/patches/service_binding_annotations.yaml

The current service binding annotations are:
service.binding/configuration: path={.status.connectionInfoRef},objectType=ConfigMap
service.binding/credentials: path={.status.credentialsRef},objectType=Secret
They shoud use the corresponding name instead as otherwise SBO won't be able to find the corresponding configmap and secret:
service.binding/configuration: path={.status.connectionInfoRef.name},objectType=ConfigMap
service.binding/credentials: path={.status.credentialsRef.name},objectType=Secret
Changes have been deployed in the lab and test done.
~~ [ ] All acceptance criteria specified in JIRA or in issue number have been completed
~~ [ ] Unit tests added that prove the fix is effective or the feature works 
~~  [ ] Documentation added for the feature

Correct service binding annotations

---

config/rbac/dbaasprovider_viewer_role_binding.yaml
config/rbac/kustomization.yaml

Add view permissions for DBaaSProvider resources for all authenticated users so that the UX can fetch & list providers regardless of the current namespace. Refer to security ADR for further info under 'Tenant Registration'.

open DBaaSProvider view to all auth'd users

---

controllers/dbaas_reconciler.go
controllers/dbaasinventory_controller.go
controllers/dbaasinventory_controller_test.go
controllers/dbaastenant_controller.go
controllers/suite_test.go
main.go

We need to ensure tenant/inventory rbac is properly configured immediately upon any authz modification. This change accomplishes that by doing the following:
- when an inventory in a tenant's namespace is reconciled, we also reconcile all related tenant rbac objects.
- when a tenant is reconciled, we also reconcile all related inventory rbac objects.

[DBAAS-141] improve reconciles of inventory and tenant objects

---

Makefile

This PR is to upgrade opm to version 1.17.3. Existing version 1.15.1 causes the catalog-build phase to fail on Mac OS.
./bin/opm index add --container-tool docker --mode semver --tag quay.io/sgahlot/dbaas-operator-catalog:v0.0.1 --bundles quay.io/sgahlot/dbaas-operator-bundle:v0.0.1
INFO[0000] building the index                            bundles="[quay.io/sgahlot/dbaas-operator-bundle:v0.0.1]"
Error: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
Usage:
opm index add [flags]
This build error is fixed with the new version.

Upgrade opm to version 1.17.3

---

.github/CODEOWNERS
.github/workflows/golangci-lint.yml
Makefile
README.md
api/v1alpha1/dbaasconnection_webhook_test.go
api/v1alpha1/webhook_suite_test.go
controllers/dbaas_controllers_common_test.go
controllers/suite_test.go

Fixed golint issue and added golint cli in the workflow
updated list of owners 
updated `make release` commands in two separated commands `make release-build` `make release-push` to avoid push to the quay.io
run commands `make help` check if new command `release-build` `release-push`,  added into the help
verify `make release-build`, `make release-push` working

Minor fixes in golint added more owners and updated makefile

---

controllers/dbaas_reconciler.go
controllers/dbaas_reconciler_test.go
controllers/dbaasinventory_controller.go
controllers/dbaasinventory_controller_test.go
controllers/dbaastenant_controller.go

- added check to ensure we aren't creating roles with edit permissions, mostly to check against potential future changes.
- also, remove unnecessary list/watch verbs from existing tenant roles.

add role check for edit & list verbs

---

bundle/manifests/dbaas-operator-edit-dedicated-admins_rbac.authorization.k8s.io_v1_rolebinding.yaml
config/rbac/dedicated_admin_namespace_edit_role_binding.yaml
config/rbac/kustomization.yaml

(please disregard branch name implying semver bump, we ended up not versioning for this change)
Adding permissions that will allow avoidance of cluster-admin roles for OSD/ROSA installations

adding edit perms for dedicated-admins

---

.gitignore
api/v1alpha1/dbaasprovider.go
config/manager/manager.yaml
controllers/dbaas_controllers_common_test.go
controllers/dbaas_reconciler.go
controllers/dbaas_reconciler_test.go
controllers/dbaasconnection_controller.go
controllers/dbaasconnection_controller_test.go
controllers/dbaasinventory_controller.go
controllers/dbaasinventory_controller_test.go
controllers/dbaasplatform_controller.go
controllers/dbaasprovider_controller_test.go
controllers/suite_test.go
go.mod
main.go

This PR is to implement https://issues.redhat.com/browse/DBAAS-201 and enhance the reconciliation logic so that the operator sets the appropriate status for the DBaaSConnection and DBaaSInventory CRs. Typical cases include:
1) There is no tenant configured for the DBaaSInventory CR in the namespace
2) There is no valid provider found for the DBaaSInventory CR
3) The inventory for the DBaaSConnection CR does not exist
4) The provider of the inventory for the DBaaSConnection CR is not valid
5) The inventory for the DBaaSConnection CR is not ready, ie, service discovery has not been completed successfully
In this PR, a new "Ready" condition type is added to DBaaSInventory and DBaaSConnection status conditions along with existing conditions synced from provider operators.
There are two …

DBAAS-201 DBaaS Operator error handling enhancements

---

controllers/dbaasconnection_controller.go
controllers/dbaasinventory_controller.go

This PR provides a quick fix for issue #85. When reconciliation returns with temporary errors (which will be reconciled again later), there is no status update needed.
Rerun the test case.
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] Code Review completed

Fix issue 85: DBaaSConnection conditions reconcile error

---

controllers/dbaasplatform_controller.go
controllers/reconcilers/constants.go
controllers/reconcilers/csv.go

This PR is to remove the variable DBAAS_CSV from constants.go because the information is already provided by the environment variable  OPERATOR_CONDITION_NAME in the dbaas operator pod. This fix also allows developers to do the dbaas operator local build without manually modifying the Makefile and constants.go file (by setting the environment variables before the build).
Do a local build with a version 0.4.1-dev different from 0.1.3, and then deploy the operator in a clean cluster.
Prior to this fix, the deployment would fail with error like:
https://github.com/RHEcosystemAppEng/dbaas-operator/blob/main/controllers/reconcilers/constants.go#L20
I got deployment error
ERROR	setup	unable to create controller	{"controller": "DBaaSPlatform", "error": "could not create dbaas platform …

Remove DBAAS_CSV from constants.go

---

PROJECT
api/v1alpha1/dbaasinventory_webhook.go
api/v1alpha1/dbaasinventory_webhook_test.go
api/v1alpha1/dbaasprovider.go
api/v1alpha1/webhook_suite_test.go
bundle/manifests/dbaas-operator.clusterserviceversion.yaml
bundle/manifests/dbaas.redhat.com_dbaasconnections.yaml
bundle/manifests/dbaas.redhat.com_dbaasinventories.yaml
config/crd/bases/dbaas.redhat.com_dbaasconnections.yaml
config/crd/bases/dbaas.redhat.com_dbaasinventories.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml
controllers/reconcilers/constants.go
controllers/reconcilers/crunchybridge_installation/crunchybridge_installation_reconciler.go
controllers/reconcilers/mongodb_atlas_instalation/mongodb_atlas_installation_reconciler.go
main.go

This PR is to add the validation logic for DBaaSInventory creation/update using a webhook along with CRD validation. The validation checks:
-- if spec.providerRef.name is provided (by CRD validation)
-- if spec.crednetialsRef.name is provided (by CRD validation). Spec.crednetialsRef.namespace can be optional and if it is empty, the default (CR's namespace) is used instead.
-- check if the mandatory fields in the credendialsRef secret are present based on the provider.
Unit test is added. Tested successfully locally.
1) Download the attached zip file and extract to a local directory.
[test2.zip](https://github.com/RHEcosystemAppEng/dbaas-operator/files/7365438/test2.zip)
2) Log on to a cluster where DBaaS operator is installed and switch to openshift-dbaas-operator namespace.
3) oc apply …

DBAAS-175 Add validation logic to DBaaSInventory creation with webhook

---

Makefile
README.md

currently makefile support build with docker, added configurable variable into CONTAINER_ENGINE to support podman build. if anyone using podman instead of docker need to set CONTAINER_ENGINE as podman** `export CONTAINER_ENGINE=podman`
verify by running command `make release-build` and make sure it's working as expected.

added CONTAINER_ENGINE option in makefile to support podman build

---

controllers/reconcilers/console_plugin/plugin_installation_reconciler.go

currently, `console-serving-cert` is used to specify a secret where openshift cert generation should store the route/service's TLS cert/key. Since we're using the same name in the annotation for both of our plugin services, we're causing an ownership issue.
```
Error while loading plugin from /api/plugins/dbaas-dynamic-plugin/ r: GET request for "dbaas-dynamic-plugin" plugin failed: Get "https://dbaas-dynamic-plugin.openshift-dbaas-operator.svc.cluster.local:9001/plugin-manifest.json": x509: certificate is valid for console-telemetry-plugin.openshift-dbaas-operator.svc, console-telemetry-plugin.openshift-dbaas-operator.svc.cluster.local, not dbaas-dynamic-plugin.openshift-dbaas-operator.svc.cluster.local
```

allow each console plugin to have its own cert secret instead of sharing one name

---

PROJECT
api/v1alpha1/dbaasinventory_webhook.go
api/v1alpha1/dbaastenant_webhook.go
api/v1alpha1/dbaastenant_webhook_test.go
api/v1alpha1/webhook_suite_test.go
config/webhook/manifests.yaml
main.go

We should only allow one tenant object per inventory namespace. The validating webhook should check if an existing tenant exists with the same spec.inventoryNamespace setting. 
https://issues.redhat.com/browse/DBAAS-379

DBAAS-379: Add webhook for dbaastenant to only allow one tenant object per inventory namespace

---

Makefile
controllers/reconcilers/constants.go

running the following command accomplishes what we need for 0.1.5. the key is using our past release as the catalog image base.
```bash
$ make generate bundle bundle-build bundle-push catalog-build catalog-push \
CATALOG_BASE_IMG=quay.io/osd-addons/dbaas-operator-index@sha256:6325f547b394b1d6f7a528ab3c01bb8f9052762acc245fd453378f5a47830923
```
testing 0.1.5 upgrade w/ `quay.io/tchughesiv/dbaas-operator-catalog:v0.1.5`
https://github.com/CrunchyData/crunchy-bridge-operator/pull/48
```bash
$ make generate bundle bundle-build catalog-build catalog-push \
CATALOG_BASE_IMG=registry.developers.crunchydata.com/crunchydata/crunchy-bridge-operator-catalog:v0.0.2 \
IMAGE_TAG_BASE=registry.developers.crunchydata.com/crunchydata/crunchy-bridge-operator \
VERSION=0.0.4
``` …

0.1.4 -> 0.1.5 bundle upgrade

---

Makefile
bundle/manifests/dbaas-operator-service-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
config/default/kustomization.yaml
config/prometheus/kustomization.yaml
config/prometheus/service_monitor.yaml
config/samples/catalog-operator-group.yaml
config/samples/mso-catalog-source-subscription.yaml
config/samples/mso.yaml
docs/install-mso.md

Signed-off-by: Rewant Soni <resoni@redhat.com>
This PR adds the configuration required for the Monitoring Stack operator and adds a new ServiceMonitor.
1. change the project from default to `dbaas-operator`
2. Update the catalog source and subscription to point to the apt image version
3. Install the operator using `make catalog-update-with-mso-install && make deploy-with-mso`
4. Port forward the Prometheus Service as `oc port-forward svc/dbaas-operator-mso-prometheus 28015:9090 -n dbaas-operator`
5. Query the metrics.

Add ServiceMonitor and MonitoringStackOperator

---

controllers/reconcilers/constants.go

related to prior change https://github.com/RHEcosystemAppEng/dbaas-operator/pull/186
for 0.2.0 we need the following built into new provider releases
https://github.com/CrunchyData/crunchy-bridge-operator/pull/52
https://github.com/cockroachdb/ccapi-k8s-operator/pull/26

[DBAAS-608] update provider operator versions for 0.2.0 release

---

api/v1alpha1/dbaasprovider.go
controllers/dbaas_reconciler.go
controllers/dbaasconnection_controller.go
controllers/dbaasconnection_controller_test.go

Move CR name from labels to annotations: label value only allows 63 characters while CR name could have 253 characters.
Update CR condition when provider CR creation fails: allow users to know the reason for provider CR creation failure. For example, pass the errors that provider operator validation webhook generates to the DBaaS CR status condition.

DBAAS-738: Move CR name from labels to annotations

---

api/v1alpha1/dbaasprovider.go
controllers/dbaas_reconciler.go
controllers/dbaasconnection_controller.go
controllers/dbaasconnection_controller_test.go

Move CR name from labels to annotations: label value only allows 63 characters while CR name could have 253 characters.
Update CR condition when provider CR creation fails: allow users to know the reason for provider CR creation failure. For example, pass the errors that provider operator validation webhook generates to the DBaaS CR status condition.

DBAAS-738: cherry pick for https://github.com/RHEcosystemAppEng/dbaas-operator/pull/195

---

Makefile
wrapper.Dockerfile

tmp fix which resolves catalog builds due to https://issues.redhat.com/browse/MTSRE-612
also upgrade opm version
e.g.
```
CATALOG_BASE_IMG=quay.io/ecosystem-appeng/dbaas-operator-catalog:0.2.0-wrapper CONTAINER_ENGINE=podman ORG=tchughesiv make generate bundle bundle-build bundle-push catalog-build
```

use catalog wrapper image until bug resolved

---

Dockerfile
Makefile
README.md
bundle.Dockerfile
bundle/manifests/dbaas-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
bundle/tests/scorecard/config.yaml
config/default/kustomization.yaml
config/default/manager-env-images.yaml
config/default/manager_auth_proxy_patch.yaml
config/embed.go
controllers/reconcilers/constants.go
controllers/reconcilers/constants_test.go
go.mod
wrapper.Dockerfile

- removes hard-coded, release-specific configs... moves images and versions to env vars. should be set in `config/default/manager-env-images.yaml`
- should env var(s) be missing, it will use default(s) via embedded yaml file
- option to use image digests in csv, w/ `make bundle-w-digests`. example of result - https://gist.github.com/tchughesiv/6b0d19518797bfe6d138b0471e45100a
- upgrade to operator-sdk v1.20.1

[DBAAS-165] leverage RELATED_IMAGE functionality for image references

---

README.md
api/v1alpha1/dbaasplatform_types.go
bundle/manifests/dbaas-operator.clusterserviceversion.yaml
config/default/manager-env-images.yaml
controllers/dbaasplatform_controller.go
controllers/reconcilers/constants.go

console-telemetry-plugin is no longer in use and should be removed from the project now.

[DBAAS-413] remove console-telemetry-plugin from RHODA stack

---

bundle/manifests/dbaas-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
controllers/reconcilers/consoleplugin/plugin_installation_reconciler.go

add `readOnlyRootFilesystem: true` to console deployment. consolidate all scc settings to containers.

[DBAAS-771] further harden deployment scc

---

api/v1alpha1/dbaasprovider.go
bundle/manifests/dbaas.redhat.com_dbaasinstances.yaml
config/crd/bases/dbaas.redhat.com_dbaasinstances.yaml
controllers/dbaas_reconciler.go
controllers/dbaasinstance_controller.go
controllers/dbaasinstance_controller_test.go
controllers/metrics.go

Add a new Instance Phase `Error`, `Failed` and `Unknown`.  
Use them to indicate cluster terminal states with issues, for example CockroachDB Cloud`CreationFailed`.
Also add kubebuilder marker to the `Phase` field to enforce restriction on the allowed values and the default value.
Jira: https://issues.redhat.com/browse/DBAAS-364
This PR doesn't change any of the existing documented values for the Instance `Phase` field. As long as the provider operators use only the documented values, nothing will need to be updated on the provider operators' side.
Changes in this PR will set the Instance `Phase` field to use value `Unknown` in the scenarios where the provider operators don't set a value for the Phase field. The provider operators are supposed to explicitly set a value for the `Phase` …

DBAAS-364: Add a new Instance Phase `Error`, `Failed` and `Unknown`

---

main.go

The existing DBaaS Operator logs uses epoch timestamps:
1.661370375316567e+09	INFO	The Operator is watching the namespace 
1.6613703753166752e+09	INFO	MongoDB Atlas Operator version v0.6.1-92-g2640489-dirty
They are not easy to read.
This PR changes the timestamps to UTC so that it is readable and easier for troubleshooting.
Check the operator logs for timestamp format:
2022-08-25T21:39:48.717Z	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": "0.0.0.0:8080"}
2022-08-25T21:39:48.717Z	INFO	controller-runtime.builder	skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called	{"GVK": "dbaas.redhat.com/v1alpha1, Kind=DBaaSConnection"}
2022-08-25T21:39:48.717Z	INFO	controller-runtime.builder	Registering a …

Enhance DBaaS Operator to have human-readable timestamps in the logs

---

api/v1alpha1/dbaasconnection_webhook.go

This PR provides a fix for the issue https://issues.redhat.com/browse/DBAAS-852 (DBaasConnection webhook fails when a CR is updated without spec changes).
The DBaaS Operator  log has the following error
tform", "name": "dbaas-platform", "namespace": "openshift-dbaas-operator", "working platform": "dbaas-dynamic-plugin"}
1.6614549767692513e+09	INFO	dbaasinventory-resource	validate update	{"name": "myinventory2"}
1.661454982158885e+09	INFO	dbaasconnection-resource	validate update	{"name": "myconnection2"}
2022/08/25 19:16:22 http: panic serving 10.130.0.1:39032: runtime error: invalid memory address or nil pointer dereference
goroutine 1580 [running]:
net/http.(*conn).serve.func1()
/usr/lib/golang/src/net/http/server.go:1802 +0xb9
panic({0x1648a60, 0x278cb40}) …

Fix DBaaSConnecton webhook ValidateUpdate crash

---

api/v1alpha1/dbaasprovider.go
config/embed.go
controllers/metrics.go
controllers/reconcilers/constants.go

Fix the warnings from linter:
$ make lint
go install golang.org/x/tools/cmd/goimports@v0.1.11
go install github.com/mgechev/revive@v1.2.1
goimports -d .
revive -config ./config.toml ./...
config/embed.go:7:1: comment on exported var EnvImages should be of the form "EnvImages ..."
controllers/reconcilers/constants.go:64:2: comment on exported const ObservabilityName should be of the form "ObservabilityName ..."
api/v1alpha1/dbaasprovider.go:70:2: exported const InstancePhaseUnknown should have comment (or a comment on this block) or be unexported
controllers/metrics.go:35:2: const metricLabelInstanceId should be metricLabelInstanceID
After the fix:
$ make lint
go install golang.org/x/tools/cmd/goimports@v0.1.11
go install github.com/mgechev/revive@v1.2.1
goimports -d .
revive -config …

Fix linter warnings

---

.github/workflows/lint.yml
api/v1alpha1/dbaasinventory_webhook.go
api/v1alpha1/dbaasinventory_webhook_test.go
api/v1alpha1/dbaaspolicy_types.go
api/v1alpha1/dbaaspolicy_webhook.go
api/v1alpha1/dbaaspolicy_webhook_test.go
api/v1alpha1/webhook_suite_test.go
api/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/dbaas-operator.clusterserviceversion.yaml
bundle/manifests/dbaas.redhat.com_dbaasinventories.yaml
bundle/manifests/dbaas.redhat.com_dbaaspolicies.yaml
config/crd/bases/dbaas.redhat.com_dbaasinventories.yaml
config/crd/bases/dbaas.redhat.com_dbaaspolicies.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml
controllers/dbaas_reconciler.go
controllers/dbaasconnection_controller_test.go
controllers/dbaasdefaultpolicy_controller.go
controllers/dbaasinstance_controller_test.go
controllers/dbaaspolicy_controller.go
controllers/metrics.go
main.go

Support for setting namespace [label selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/). The following can be set in policy and/or inventory objects.
```yaml
spec:
connectionNsSelector:
matchExpressions:
- key: test
operator: NotIn
values:
- production
matchLabels:
- foo: one
- two: bar
```

[DBAAS-887] add selector option for valid DBaaS Connection/Instance namespaces

---

.github/workflows/gotest.yml
Makefile

We'll require at least 70% coverage for modified files.
an example of coverage passing the threshold -
```
github.com/RHEcosystemAppEng/dbaas-operator/controllers/dbaasinstance_controller.go:49:		Reconcile		86.7%
github.com/RHEcosystemAppEng/dbaas-operator/controllers/dbaasinstance_controller.go:111:	SetupWithManager	100.0%
github.com/RHEcosystemAppEng/dbaas-operator/controllers/dbaasinstance_controller.go:122:	mergeInstanceStatus	100.0%
github.com/RHEcosystemAppEng/dbaas-operator/controllers/dbaasinstance_controller.go:146:	Delete			80.0%
total:												(statements)		87.5%
Quality Gate: checking test coverage is above threshold ...
Threshold             : 70 %
Current test coverage : 87.5 %
OK
```
an example of it failing -
``` …
```

[DBAAS-975] add coverage check action

---

controllers/suite_test.go

resolves this issue - 
https://github.com/kubernetes-sigs/controller-runtime/issues/1571
resolves hanging processes as well
```bash
501 41503     1   0 10:41AM ttys000    1:13.34 /Users/<user>/workspace/dbaas-operator/bin/k8s/1.24.2-darwin-arm64/etcd --advertise-client-urls=http://127.0.0.1:50533 ...
501 41507     1   0 10:41AM ttys000    6:52.17 /Users/<user>/workspace/dbaas-operator/bin/k8s/1.24.2-darwin-arm64/kube-apiserver --allow-privileged=true ...
```

[DBAAS-974] fix envtest timeout waiting for process kube-apiserver to stop

---

controllers/dbaasconnection_controller.go
controllers/dbaasinstance_controller.go
controllers/dbaasinventory_controller.go
controllers/dbaasplatform_controller.go
controllers/metrics/dbaas_connection_metrics.go
controllers/metrics/dbaas_inventory_metrics.go
controllers/metrics/metrics.go
main.go

DBaaSConnection metrics based on the design proposal at this [link](https://docs.google.com/presentation/d/1R9jdTdBwDp70Xlr9r_83nsbG7JUqA8I0DsnKE_N3hsk/edit?usp=sharing)
Prometheus Output Console
* Please check screenshot of the Prometheus output [here](https://docs.google.com/document/d/1EA4U7mFSQHsq8xS-cfvPuQ7BxdUh9ziCE0OZZKF-H_0/edit?usp=sharing)
* On fresh Openshift Local instance, in a terminal window login with admin credentials and deploy DBaaS Operator 
```shell
oc apply -f config/samples/installation-for-non-OSD-OCP-environments.yaml
```
* Once the DBaaS Operator is fully installed, expose the Prometheus service and navigate to the prometheus service in the browser
```shell
oc project openshift-dbaas-operator
oc expose svc/prometheus-operated
oc get route
```
* Deploy Mongo Quick …

[DBAAS-1044] DBaaS Connection Resource Metrics Addition

---

controllers/dbaasplatform_controller.go
controllers/metrics/dbaas_connection_metrics.go
controllers/metrics/dbaas_instance_metrics.go
controllers/metrics/dbaas_inventory_metrics.go
controllers/metrics/dbaas_platform_metrics.go
controllers/metrics/metrics.go

DBaaSPlatform Metrics Initial Implementation
Add the steps required to check this change. Following an example.
1. Install the DBaaS Operator on a fresh OpenShift cluster.
2. After successful installation expose the Prometheus service
`
oc project openshift-dbaas-operator;
oc expose svc/prometheus-operated;
oc get route;
`
3. Navigate to Prometheus Service Route in the browser, select a metric such as "dbaas_requests_duration_seconds_sum" and see the resource="dbaas_platform" appear.

[DBAAS-1092]-DBaaSPlatform Metrics Initial Implementation

---

controllers/metrics/dbaas_connection_metrics.go
controllers/metrics/dbaas_instance_metrics.go
controllers/metrics/dbaas_inventory_metrics.go
controllers/metrics/dbaas_platform_metrics.go

Remove logging from setConnectionStatusMetrics as it generates too much of logs
The multiple logs from setConnectionStatusMetrics should not appear, as they are deleted

[DBAAS-1092] Remove logging from setConnectionStatusMetrics

---

bundle/metadata/dependencies.yaml

This change is causing issues during platform install. This change should be resubmitted at the same time as the RDS operator version/build is incremented, which would include https://github.com/RHEcosystemAppEng/rds-dbaas-operator/pull/15

Revert "DBAAS-941: upgrade to RDS controller v0.1.1"

---

api/v1alpha1/dbaasinstance_conversion.go
api/v1alpha1/dbaasprovider_conversion.go

setting the default value for cloud provider region parameter `us-east-1` for crunchy bridge operator trial version, as the dbaas instance cr only set cloud provider default aws. 
```spec:
inventoryRef:
name: ahameed-r5
namespace: openshift-dbaas-operator
provisioningParameters:
cloudProvider: aws
name: dbaastest
plan: FREETRIAL
teamProject: '': ''
```
setting region and removing the teamProject from cr, as it's not required for trail version, and it will get default.   
```
spec:
cloudProvider: aws
cloudRegion: us-east-1
inventoryRef:
name: ahameed-r5
namespace: openshift-dbaas-operator
name: dbaastest
otherInstanceParams:
Name: dbaastest
Provider: aws
```
Removing the TeamID parameters as these are not required and avoid passing empty or …

fix the issue with crunchy operator for trial version cluster creation

---

bundle/manifests/dbaas-operator.clusterserviceversion.yaml
config/default/manager-env-images.yaml

CRDB image is pushed (v0.0.5 to match RHODA 0.4.0), update back to their repo

update CRDB image pointer back to official repo

---

controllers/dbaas_controllers_common_test.go
controllers/dbaasplatform_controller.go
controllers/dbaasplatform_controller_test.go

With ack-rds-controller v0.1.3, the label selector of the deployment of the operator is changed. 
However, this field is immutable. 
As a result, upgrading ack-rds-controller from an older version to v0.1.3 fails.
Jira: https://issues.redhat.com/browse/DBAAS-1193
The workaround is to use the RHODA operator to check the status of the ack-rds-controller v0.1.3 csv. 
If the upgrade issue is detected, RHODA operator will delete the deployment of the ack-rds-controller.
Then the deployment of the ack-rds-controller will be re-created automatically, and the upgrade will contiune.
Upgrading RHODA v0.0.3 to 0.0.4.
Check if the upgrade succeeds and if the ack-rds-controller is upgraded to v0.1.3.

DBAAS-1193: workaround to the ack-rds-controller v0.1.3 upgrade issue

---

controllers/dbaasplatform_controller.go
controllers/metrics/dbaas_connection_metrics.go
controllers/metrics/dbaas_instance_metrics.go
controllers/metrics/dbaas_inventory_metrics.go
controllers/metrics/metrics.go

adding back the creation time label in metrics for invenotry/connection/istnance to know when the these object created, and to show on grafana.  

Fix metrics to show creation time of objects on grafana dashboard

---

controllers/dbaasconnection_controller.go
controllers/dbaasinstance_controller.go
controllers/dbaasinventory_controller.go
controllers/dbaasplatform_controller.go
controllers/dbaaspolicy_controller.go
controllers/dbaasprovider_controller.go
controllers/metrics/dbaas_connection_metrics.go
controllers/metrics/dbaas_instance_metrics.go
controllers/metrics/dbaas_inventory_metrics.go
controllers/metrics/dbaas_policy_metrics.go
controllers/metrics/dbaas_provider_metrics.go

set log verbosity level to show some of the logs in just debugging mod.
Add the steps required to check this change. Following an example.
1. Deploy the operator 
2. change the level debug for manager container -> `--zap-log-level=debug` can be done in editing CSV file
```
args:
- '--health-probe-bind-address=:8081'
- '--metrics-bind-address=0.0.0.0:8080'
- '--leader-elect'
- '--zap-log-level=debug'
```
5.verify the debug log is showing.
``` 2023-02-13T17:03:49.224Z DEBUG DBaaSConnectionReconciler DeleteEvent Delete event started
2023-02-13T17:03:49.224Z DEBUG DBaaS Connection resource not found, has been deleted {"controller": "dbaasconnection", "controllerGroup": "dbaas.redhat.com", "controllerKind": "DBaaSConnection", "DBaaSConnection": …
```

[DBAAS-1103 ]setting log verbosity level
